[build]
  publish = "public"
  functions = "functions"

[functions]
  gpt = { timeout = 26 }  # Set timeout for the "gpt" function to 26 seconds

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
